### PR TITLE
FreeBSD defines major/minor

### PR DESCRIPTION
**Pull request by gahr**

### CODE REVIEW

**Comment by mpenick** [comment]
Thanks! This could be a problem on other *nix platforms (not just FreeBSD) and to make it more complex sometimes they're not macro, but inlined functions. I wonder if we should rename those params / methods.

**Comment by gena01** [comment]
@mpenick Seems that Alpine Linux has a similar problem (need it for Docker image/container...)

**Comment by mpenick** [comment]
Adding fix in the next release: https://datastax-oss.atlassian.net/browse/CPP-345

**Comment by mpenick** [comment]
Fix: https://github.com/datastax/cpp-driver/pull/262 up for review.

**Comment by mikefero** [comment]
Thanks for the contribution @gahr; #262 has been merged into master.

**Comment by gahr** [comment]
Thanks @mikefero!

**Pull request closed without merging**
