### PR TITLE
Add WhitelistDC, Blacklist and BalcklistDC policies

### PR DESCRIPTION
**Pull request by waitamer**
It is time saving when we want to whitelist a hole dc with many hosts.
We can blacklist a dc instead of whitelisting all other hosts of other dcs.
We can also blacklist some hosts.

### CODE REVIEW

**Comment by mpenick** [comment]
Thanks for the load balancing policies. I'm currently working on a php-driver release. I'll attempt to review this next week. Sorry for the delay.

**Comment by waitamer** [comment]
OK thanks !

**Comment by waitamer** [comment]
Hello 
Did you review my commit ?
Thanks

**Comment by mpenick** [comment]
I will start review later today.

**Comment by mpenick** [comment]
@waitamer looks great. Thanks for adding these (with tests). Sorry this took so long.

**Comment by waitamer** [comment]
Thanks !

**Pull request merged**
